fun main(){
//    val s1: String? = "23"
//    val i: Int = s1!!.toInt()
//    println(i)
//    val s2 = readln().toInt()
//    println(s2)
    println("Enter Enrollment Number:")
    val eno = readln()
    println("Enter Name:")
    val name = readln()
    println("Enter Branch:")
    val branch = readln()
    println("Enter Class:")
    val clas = readln()
    println("Enter Batch:")
    val batch = readln()
    println("Enter College Name:")
    val clg = readln()
    println("Enter University Name:")
    val uni = readln()
    println("Enter Age:")
    val age = readln().toInt()

    println("Student's Data:")
    println("Enrollment No.:$eno")
    println("Name: $name")
    println("Age: $age")
    println("Branch: $branch")
    println("Class: $clas")
    println("Batch: $batch")
    println("College Name: $clg")
    println("University Name: $uni")

}